extends:
  - eslint-config-ali/react
parser: babel-eslint
plugins:
  - react
  - compat
  - import
  - jsx-a11y
  - typescript
  - react-hooks
env:
  es6: true
  browser: true
  node: true
  jest: true
settings:
  import/resolver:
    node:
      moduleDirectory:
        - node_modules
        - app
        - router
        - router/modules
rules:
  arrow-body-style: 0
  max-len: 0
  no-unused-vars: 1
  no-nested-ternary: 0
  react/prop-types: 0
  react/jsx-first-prop-new-line: 0
  react/no-multi-comp: 0
  react/no-unused-prop-types: 0
  react/jsx-filename-extension:
    - 1
    - extensions:
      - '.js'
      - '.jsx'
      - '.tsx'
  import/prefer-default-export: 0
  import/no-named-as-default: 0
  import/no-named-as-default-member: 0
  react-hooks/rules-of-hooks: "error"
overrides:
  - files: ["*.tsx","*.ts"]
    parser: "@typescript-eslint/parser"
    extends:
      - eslint-config-ali/react
      - eslint-config-ali/typescript
    parserOptions:
      project:
        - "./tsconfig.json"
    rules:
      "@typescript-eslint/consistent-type-assertions": 0
      react/no-unused-prop-types: 0
      max-len: 0
      no-undef: 0
      no-nested-ternary: 0
      no-restricted-globals: 0
      no-unused-vars: 1
